config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "customers#index"

  resources :customers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  def self.all_customers(user_id)
    Customer.find_by_sql(
      "SELECT *
      FROM customers AS c
      WHERE c.user_id = #{user_id}"
    )
  end
   #using a different way to inturpulation data
   # ? is holding space for inturpulation, order is important
  def self.single_customer(user_id, customer_id)
    Customer.find_by_sql(["
      SELECT * 
      FROM customers AS c
      WHERE c.id = ? AND c.user_id = ? 
      ", customer_id, user_id]).first
    #.first will show a instance instead of the array
  end

  def self.create_customer(p, user_id)
    Customer.find_by_sql(["
      INSERT INTO customers (first_name, last_name, email, phone, user_id, created_at, updated_at)
      VALUES (:first, :last, :email, :phone, :user_id, :created_at, :updated_at )
      ", {
        first: p[:fisrt_name],
        last: p[:last_name],
        email: p[:email],
        phone: p[:phone],
        user_id: user_id,
        created_at: DateTime.now,
        updated_at: DateTime.now
      }])
  end

  def self.delete_customer(customer_id)
    Customer.find_by_sql(["
      DELETE FROM customers AS c
      WHERE c.id = ?
    ;", customer_id])
  end

  def self.update_customer(customer_id, p)
    Customer.find_by_sql(["
      UPDATE customers AS c
      SET first_name = ?, last_name = ?, email = ?, phone = ?, updated_at = ?
      WHERE c.id = ?
    ;", p[:first_name], p[:last_name], p[:email], p[:phone], DateTime.now, customer_id])
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  #SELECT all reocords that belong  to User
  def index
  @customers = Customer.all_customers(current_user.id)
  end

  def show
  end

  def new
    @customer = current_user.customers.new
  end
  def create
  #INSERT one record
  Customer.create_customer(customer_params, current_user.id)
  redirect_to customers_path
  end

  def edit
  end

  def update
    Customer.update_customer(@customer.id, customer_params)
    redirect_to customers_path
  end

  def destroy
    Customer.delete_customer(@customer.id)
    redirect_to customers_path
  end

private
def set_customer
  #SELECT single record sql way
  @customer = Customer.single_customer(current_user.id, params[:id])
end

def customer_params
  params.require(:customer).permit(:first_name, :last_name, :email, :phone)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: @customer, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "input" %>
  </div>
 <div class="field">
   <%= f.label :last_name %>
   <%= f.text_field :last_name, class: "input" %>
 </div>
 <div class="field">
   <%= f.label :email %>
   <%= f.text_field :email, class: "input" %>
 </div>
 <div class="field">
   <%= f.label :phone %>
   <%= f.text_field :phone, class: "input" %>
 </div>
 <%= f.submit nil, class: "ui blue button" %>
<% end %>

app/views/customers/edit.html.erb
<h1>Edit Customer</h1>

<%= render "form"%>

app/views/customers/index.html.erb
<h1> Customers</h1>
<% @customers.each do |customer| %>
<div>
<h3><%= link_to customer.full_name, customer_path(customer) %></h3>
</div>
<% end %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render "form"%>

app/views/customers/show.html.erb
<h1><%= @customer.full_name %></h1>

<%= link_to "Edit", edit_customer_path(@customer), class: "ui orange button"%>
<%= link_to "Delete", @customer, method: :delete, class: "ui orange button"%>

app/views/layouts/_navbar.html.erb
<nav class="ui menu">
  <%= link_to "Customers", customers_path, class: "item" %>
  <%= link_to "Add Customer", new_customer_path, class: "item" %>
  <div class="right menu">
    <% if current_user %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "item" %>
    <% else %>
      <%= link_to "Register", new_user_registration_path, class: "item" %>
      <%= link_to "Login", new_user_session_path, class: "item" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Customers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
   <%= render "layouts/navbar" %>
  <div class="ui container">
    <%= yield %>
  </body>
  </div>
</html>